name: Distribute
on:
  push:
    paths:
    - '.github/workflows/distribute.yml'
    - 'Makefile'
    - 'scripts/package-lib.py'
    - 'src/example.c'
  schedule:
    - cron: '0 3 * * 0'

jobs:
  Unix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
        - os: ubuntu-latest
          OS_TAG: Linux
        - os: macos-latest
          OS_TAG: OSX

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.7'

    - name: Package
      run: |
        pip install -U h5py
        python scripts/package-lib.py

    - name: Test
      run: |
        make
        ./bin/example

    - name: Release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        automatic_release_tag: ${{ matrix.OS_TAG }}
        title: ${{ matrix.OS_TAG }}
        files: |
          libhdf5-*.tgz
        repo_token: ${{ secrets.GITHUB_TOKEN }}
